image: 715859896688.dkr.ecr.us-east-1.amazonaws.com/pipeline-x86-ubuntu:latest

before_script:
  - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )'
  - eval $(ssh-agent -s)
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add - > /dev/null
  - mkdir -p ~/.ssh
  - chmod 700 ~/.ssh
  - ssh-keyscan gitlab.boonlogic.com >> ~/.ssh/known_hosts
  - chmod 644 ~/.ssh/known_hosts
  - export PATH=~/.local/bin:$PATH

variables:
  GIT_STRATEGY: none
  GIT_SSL_NO_VERIFY: "true"
  CLANG_FORMAT: clang-format
  REF_NAME: master
  SHELL: /bin/bash

stages:
  - build
  - test-setup
  - test
  - package

build:
  stage: build
  tags:
    - expert-docker
  script:
    - chmod -Rf 755 ci-root && rm -rf ci-root || true
    - git clone git@gitlab.boonlogic.com:development/builder.git ci-root
    - cd ci-root
    - git checkout ${CI_COMMIT_REF_NAME} || true
    - BRANCH=${CI_COMMIT_REF_NAME} make amber-csharp-sdk-env
    - make amber-csharp-sdk-build
  artifacts:
    paths:
    - ci-root/

test-setup:
  stage: test-setup
  tags:
    - expert-docker
  script:
    - cd ci-root
    - BRANCH=${CI_COMMIT_REF_NAME} make amber-cli-env
    - make amber-cli-build
    - BRANCH=${CI_COMMIT_REF_NAME} make expert-api-env
    - make expert-api-build
  artifacts:
    paths:
      - ci-root/packages/amber-cli
      - ci-root/packages/expert-server

test:
  stage: test
  tags:
    - expert-docker
  before_script:
    - cd ci-root/packages/amber-cli/amber-cli
    - ./amber aop create-test-config --port 9876 > ${CI_PROJECT_DIR}/ci-root/packages/amber-csharp-sdk/amber-csharp-sdk/Amber.license
    - cd ${CI_PROJECT_DIR}/ci-root/packages/expert-server/expert-api
    - export PORT=9876
    - make start-amber-cloud
  script:
    - cd ${CI_PROJECT_DIR}/ci-root/packages/amber-csharp-sdk/amber-csharp-sdk
    - export AMBER_TEST_LICENSE_FILE=${PWD}/Amber.license
    - export AMBER_TEST_LICENSE_ID=aoc
    - DOTNET_VERSION=netcore make test

package:
  image: docker:latest
  stage: package
  tags:
    - UseDinD
  services:
    - docker:dind
  before_script:
    - apk add --no-cache curl jq python3 py-pip make git bash
    - pip install awscli
  script:
    - cd ci-root
    - make amber-csharp-sdk-package
