/*
 * Amber API Server
 *
 * Boon Logic Amber API Server
 *
 * The version of the OpenAPI document: 1.0.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BoonAmber.Api;
using BoonAmber.Model;
using BoonAmber.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BoonAmber.Test.Model
{
    /// <summary>
    ///  Class for testing FusionConfig
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class FusionConfigTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for FusionConfig
        //private FusionConfig instance;

        public FusionConfigTests()
        {
            // TODO uncomment below to create an instance of FusionConfig
            //instance = new FusionConfig();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of FusionConfig
        /// </summary>
        [Fact]
        public void FusionConfigInstanceTest()
        {
            // TODO uncomment below to test "IsType" FusionConfig
            //Assert.IsType<FusionConfig>(instance);
        }


        /// <summary>
        /// Test the property 'Label'
        /// </summary>
        [Fact]
        public void LabelTest()
        {
            // TODO unit test for the property 'Label'
        }
        /// <summary>
        /// Test the property 'SubmitRule'
        /// </summary>
        [Fact]
        public void SubmitRuleTest()
        {
            // TODO unit test for the property 'SubmitRule'
        }

    }

}
