/*
 * Amber API Server
 *
 * Boon Logic Amber API Server
 *
 * The version of the OpenAPI document: 1.0.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BoonAmber.Api;
using BoonAmber.Model;
using BoonAmber.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BoonAmber.Test.Model
{
    /// <summary>
    ///  Class for testing MStreamingParameters
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MStreamingParametersTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MStreamingParameters
        //private MStreamingParameters instance;

        public MStreamingParametersTests()
        {
            // TODO uncomment below to create an instance of MStreamingParameters
            //instance = new MStreamingParameters();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MStreamingParameters
        /// </summary>
        [Fact]
        public void MStreamingParametersInstanceTest()
        {
            // TODO uncomment below to test "IsType" MStreamingParameters
            //Assert.IsType<MStreamingParameters>(instance);
        }


        /// <summary>
        /// Test the property 'VersionNumber'
        /// </summary>
        [Fact]
        public void VersionNumberTest()
        {
            // TODO unit test for the property 'VersionNumber'
        }
        /// <summary>
        /// Test the property 'MEnableAutotuning'
        /// </summary>
        [Fact]
        public void MEnableAutotuningTest()
        {
            // TODO unit test for the property 'MEnableAutotuning'
        }
        /// <summary>
        /// Test the property 'MSamplesToBufferForAutotuning'
        /// </summary>
        [Fact]
        public void MSamplesToBufferForAutotuningTest()
        {
            // TODO unit test for the property 'MSamplesToBufferForAutotuning'
        }
        /// <summary>
        /// Test the property 'MGraduationAtRateNumerator'
        /// </summary>
        [Fact]
        public void MGraduationAtRateNumeratorTest()
        {
            // TODO unit test for the property 'MGraduationAtRateNumerator'
        }
        /// <summary>
        /// Test the property 'MGraduationAtRateDenominator'
        /// </summary>
        [Fact]
        public void MGraduationAtRateDenominatorTest()
        {
            // TODO unit test for the property 'MGraduationAtRateDenominator'
        }
        /// <summary>
        /// Test the property 'MGraduateAtMaxClusters'
        /// </summary>
        [Fact]
        public void MGraduateAtMaxClustersTest()
        {
            // TODO unit test for the property 'MGraduateAtMaxClusters'
        }
        /// <summary>
        /// Test the property 'MGraduateAtMaxSamples'
        /// </summary>
        [Fact]
        public void MGraduateAtMaxSamplesTest()
        {
            // TODO unit test for the property 'MGraduateAtMaxSamples'
        }

    }

}
