/*
 * Amber API Server
 *
 * Boon Logic Amber API Server
 *
 * The version of the OpenAPI document: 1.0.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BoonAmber.Api;
using BoonAmber.Model;
using BoonAmber.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BoonAmber.Test.Model
{
    /// <summary>
    ///  Class for testing PostConfigResponseAllOf
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PostConfigResponseAllOfTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PostConfigResponseAllOf
        //private PostConfigResponseAllOf instance;

        public PostConfigResponseAllOfTests()
        {
            // TODO uncomment below to create an instance of PostConfigResponseAllOf
            //instance = new PostConfigResponseAllOf();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PostConfigResponseAllOf
        /// </summary>
        [Fact]
        public void PostConfigResponseAllOfInstanceTest()
        {
            // TODO uncomment below to test "IsType" PostConfigResponseAllOf
            //Assert.IsType<PostConfigResponseAllOf>(instance);
        }


        /// <summary>
        /// Test the property 'FeatureCount'
        /// </summary>
        [Fact]
        public void FeatureCountTest()
        {
            // TODO unit test for the property 'FeatureCount'
        }
        /// <summary>
        /// Test the property 'StreamingWindowSize'
        /// </summary>
        [Fact]
        public void StreamingWindowSizeTest()
        {
            // TODO unit test for the property 'StreamingWindowSize'
        }
        /// <summary>
        /// Test the property 'Features'
        /// </summary>
        [Fact]
        public void FeaturesTest()
        {
            // TODO unit test for the property 'Features'
        }
        /// <summary>
        /// Test the property 'SamplesToBuffer'
        /// </summary>
        [Fact]
        public void SamplesToBufferTest()
        {
            // TODO unit test for the property 'SamplesToBuffer'
        }
        /// <summary>
        /// Test the property 'PercentVariationOverride'
        /// </summary>
        [Fact]
        public void PercentVariationOverrideTest()
        {
            // TODO unit test for the property 'PercentVariationOverride'
        }

    }

}
