/*
 * Amber API Server
 *
 * Boon Logic Amber API Server
 *
 * The version of the OpenAPI document: 1.0.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BoonAmber.Api;
using BoonAmber.Model;
using BoonAmber.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BoonAmber.Test.Model
{
    /// <summary>
    ///  Class for testing PostStreamResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PostStreamResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PostStreamResponse
        //private PostStreamResponse instance;

        public PostStreamResponseTests()
        {
            // TODO uncomment below to create an instance of PostStreamResponse
            //instance = new PostStreamResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PostStreamResponse
        /// </summary>
        [Fact]
        public void PostStreamResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" PostStreamResponse
            //Assert.IsType<PostStreamResponse>(instance);
        }


        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
        /// <summary>
        /// Test the property 'Progress'
        /// </summary>
        [Fact]
        public void ProgressTest()
        {
            // TODO unit test for the property 'Progress'
        }
        /// <summary>
        /// Test the property 'ClusterCount'
        /// </summary>
        [Fact]
        public void ClusterCountTest()
        {
            // TODO unit test for the property 'ClusterCount'
        }
        /// <summary>
        /// Test the property 'RetryCount'
        /// </summary>
        [Fact]
        public void RetryCountTest()
        {
            // TODO unit test for the property 'RetryCount'
        }
        /// <summary>
        /// Test the property 'StreamingWindowSize'
        /// </summary>
        [Fact]
        public void StreamingWindowSizeTest()
        {
            // TODO unit test for the property 'StreamingWindowSize'
        }
        /// <summary>
        /// Test the property 'TotalInferences'
        /// </summary>
        [Fact]
        public void TotalInferencesTest()
        {
            // TODO unit test for the property 'TotalInferences'
        }
        /// <summary>
        /// Test the property 'RI'
        /// </summary>
        [Fact]
        public void RITest()
        {
            // TODO unit test for the property 'RI'
        }
        /// <summary>
        /// Test the property 'SI'
        /// </summary>
        [Fact]
        public void SITest()
        {
            // TODO unit test for the property 'SI'
        }
        /// <summary>
        /// Test the property 'AD'
        /// </summary>
        [Fact]
        public void ADTest()
        {
            // TODO unit test for the property 'AD'
        }
        /// <summary>
        /// Test the property 'AH'
        /// </summary>
        [Fact]
        public void AHTest()
        {
            // TODO unit test for the property 'AH'
        }
        /// <summary>
        /// Test the property 'AM'
        /// </summary>
        [Fact]
        public void AMTest()
        {
            // TODO unit test for the property 'AM'
        }
        /// <summary>
        /// Test the property 'AW'
        /// </summary>
        [Fact]
        public void AWTest()
        {
            // TODO unit test for the property 'AW'
        }
        /// <summary>
        /// Test the property 'ID'
        /// </summary>
        [Fact]
        public void IDTest()
        {
            // TODO unit test for the property 'ID'
        }

    }

}
