/*
 * Amber API Server
 *
 * Boon Logic Amber API Server
 *
 * The version of the OpenAPI document: 1.0.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BoonAmber.Api;
using BoonAmber.Model;
using BoonAmber.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BoonAmber.Test.Model
{
    /// <summary>
    ///  Class for testing PutConfigRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PutConfigRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PutConfigRequest
        //private PutConfigRequest instance;

        public PutConfigRequestTests()
        {
            // TODO uncomment below to create an instance of PutConfigRequest
            //instance = new PutConfigRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PutConfigRequest
        /// </summary>
        [Fact]
        public void PutConfigRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" PutConfigRequest
            //Assert.IsType<PutConfigRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Features'
        /// </summary>
        [Fact]
        public void FeaturesTest()
        {
            // TODO unit test for the property 'Features'
        }
        /// <summary>
        /// Test the property 'Streaming'
        /// </summary>
        [Fact]
        public void StreamingTest()
        {
            // TODO unit test for the property 'Streaming'
        }

    }

}
