/*
 * Amber API Server
 *
 * Boon Logic Amber API Server
 *
 * The version of the OpenAPI document: 1.0.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BoonAmber.Api;
using BoonAmber.Model;
using BoonAmber.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BoonAmber.Test.Model
{
    /// <summary>
    ///  Class for testing PutStreamRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PutStreamRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PutStreamRequest
        //private PutStreamRequest instance;

        public PutStreamRequestTests()
        {
            // TODO uncomment below to create an instance of PutStreamRequest
            //instance = new PutStreamRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PutStreamRequest
        /// </summary>
        [Fact]
        public void PutStreamRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" PutStreamRequest
            //Assert.IsType<PutStreamRequest>(instance);
        }


        /// <summary>
        /// Test the property 'Vector'
        /// </summary>
        [Fact]
        public void VectorTest()
        {
            // TODO unit test for the property 'Vector'
        }
        /// <summary>
        /// Test the property 'SubmitRule'
        /// </summary>
        [Fact]
        public void SubmitRuleTest()
        {
            // TODO unit test for the property 'SubmitRule'
        }

    }

}
