/*
 * Amber API Server
 *
 * Boon Logic Amber API Server
 *
 * The version of the OpenAPI document: 1.0.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BoonAmber.Api;
using BoonAmber.Model;
using BoonAmber.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BoonAmber.Test.Model
{
    /// <summary>
    ///  Class for testing GetStatusResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetStatusResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetStatusResponse
        //private GetStatusResponse instance;

        public GetStatusResponseTests()
        {
            // TODO uncomment below to create an instance of GetStatusResponse
            //instance = new GetStatusResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetStatusResponse
        /// </summary>
        [Fact]
        public void GetStatusResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetStatusResponse
            //Assert.IsType<GetStatusResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Pca'
        /// </summary>
        [Fact]
        public void PcaTest()
        {
            // TODO unit test for the property 'Pca'
        }
        /// <summary>
        /// Test the property 'ClusterGrowth'
        /// </summary>
        [Fact]
        public void ClusterGrowthTest()
        {
            // TODO unit test for the property 'ClusterGrowth'
        }
        /// <summary>
        /// Test the property 'ClusterSizes'
        /// </summary>
        [Fact]
        public void ClusterSizesTest()
        {
            // TODO unit test for the property 'ClusterSizes'
        }
        /// <summary>
        /// Test the property 'AnomalyIndexes'
        /// </summary>
        [Fact]
        public void AnomalyIndexesTest()
        {
            // TODO unit test for the property 'AnomalyIndexes'
        }
        /// <summary>
        /// Test the property 'FrequencyIndexes'
        /// </summary>
        [Fact]
        public void FrequencyIndexesTest()
        {
            // TODO unit test for the property 'FrequencyIndexes'
        }
        /// <summary>
        /// Test the property 'DistanceIndexes'
        /// </summary>
        [Fact]
        public void DistanceIndexesTest()
        {
            // TODO unit test for the property 'DistanceIndexes'
        }
        /// <summary>
        /// Test the property 'TotalInferences'
        /// </summary>
        [Fact]
        public void TotalInferencesTest()
        {
            // TODO unit test for the property 'TotalInferences'
        }
        /// <summary>
        /// Test the property 'NumClusters'
        /// </summary>
        [Fact]
        public void NumClustersTest()
        {
            // TODO unit test for the property 'NumClusters'
        }
        /// <summary>
        /// Test the property 'AnomalyThreshold'
        /// </summary>
        [Fact]
        public void AnomalyThresholdTest()
        {
            // TODO unit test for the property 'AnomalyThreshold'
        }
        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }

    }

}
