/*
 * Amber API Server
 *
 * Boon Logic Amber API Server
 *
 * The version of the OpenAPI document: 1.0.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BoonAmber.Api;
using BoonAmber.Model;
using BoonAmber.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BoonAmber.Test.Model
{
    /// <summary>
    ///  Class for testing GetSensorsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetSensorsResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetSensorsResponse
        //private GetSensorsResponse instance;

        public GetSensorsResponseTests()
        {
            // TODO uncomment below to create an instance of GetSensorsResponse
            //instance = new GetSensorsResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetSensorsResponse
        /// </summary>
        [Fact]
        public void GetSensorsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetSensorsResponse
            //Assert.IsType<GetSensorsResponse>(instance);
        }



    }

}
