/*
 * Amber API Server
 *
 * Boon Logic Amber API Server
 *
 * The version of the OpenAPI document: 1.0.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BoonAmber.Api;
using BoonAmber.Model;
using BoonAmber.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BoonAmber.Test.Model
{
    /// <summary>
    ///  Class for testing GetSensorResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GetSensorResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GetSensorResponse
        //private GetSensorResponse instance;

        public GetSensorResponseTests()
        {
            // TODO uncomment below to create an instance of GetSensorResponse
            //instance = new GetSensorResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GetSensorResponse
        /// </summary>
        [Fact]
        public void GetSensorResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" GetSensorResponse
            //Assert.IsType<GetSensorResponse>(instance);
        }


        /// <summary>
        /// Test the property 'Label'
        /// </summary>
        [Fact]
        public void LabelTest()
        {
            // TODO unit test for the property 'Label'
        }
        /// <summary>
        /// Test the property 'SensorId'
        /// </summary>
        [Fact]
        public void SensorIdTest()
        {
            // TODO unit test for the property 'SensorId'
        }
        /// <summary>
        /// Test the property 'UsageInfo'
        /// </summary>
        [Fact]
        public void UsageInfoTest()
        {
            // TODO unit test for the property 'UsageInfo'
        }

    }

}
