/* 
 * Amber API Server
 *
 * Boon Logic Amber API Server
 *
 * OpenAPI spec version: 1.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BoonAmber.Api;
using BoonAmber.Model;
using BoonAmber.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BoonAmber.Test
{
    /// <summary>
    ///  Class for testing MAmberStatus
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MAmberStatusTests
    {
        // TODO uncomment below to declare an instance variable for MAmberStatus
        //private MAmberStatus instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MAmberStatus
            //instance = new MAmberStatus();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MAmberStatus
        /// </summary>
        [Test]
        public void MAmberStatusInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MAmberStatus
            //Assert.IsInstanceOfType<MAmberStatus> (instance, "variable 'instance' is a MAmberStatus");
        }


        /// <summary>
        /// Test the property 'VersionNumber'
        /// </summary>
        [Test]
        public void VersionNumberTest()
        {
            // TODO unit test for the property 'VersionNumber'
        }
        /// <summary>
        /// Test the property 'MStatus'
        /// </summary>
        [Test]
        public void MStatusTest()
        {
            // TODO unit test for the property 'MStatus'
        }
        /// <summary>
        /// Test the property 'MMessage'
        /// </summary>
        [Test]
        public void MMessageTest()
        {
            // TODO unit test for the property 'MMessage'
        }
        /// <summary>
        /// Test the property 'MProgress'
        /// </summary>
        [Test]
        public void MProgressTest()
        {
            // TODO unit test for the property 'MProgress'
        }
        /// <summary>
        /// Test the property 'MCurrentClusterCount'
        /// </summary>
        [Test]
        public void MCurrentClusterCountTest()
        {
            // TODO unit test for the property 'MCurrentClusterCount'
        }
        /// <summary>
        /// Test the property 'MRetryCount'
        /// </summary>
        [Test]
        public void MRetryCountTest()
        {
            // TODO unit test for the property 'MRetryCount'
        }
        /// <summary>
        /// Test the property 'MStreamingWindowSize'
        /// </summary>
        [Test]
        public void MStreamingWindowSizeTest()
        {
            // TODO unit test for the property 'MStreamingWindowSize'
        }
        /// <summary>
        /// Test the property 'MTotalInferences'
        /// </summary>
        [Test]
        public void MTotalInferencesTest()
        {
            // TODO unit test for the property 'MTotalInferences'
        }
        /// <summary>
        /// Test the property 'MTotalSamplesWritten'
        /// </summary>
        [Test]
        public void MTotalSamplesWrittenTest()
        {
            // TODO unit test for the property 'MTotalSamplesWritten'
        }

    }

}
