/*
 * Amber API Server
 *
 * Boon Logic Amber API Server
 *
 * The version of the OpenAPI document: 1.0.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BoonAmber.Api;
using BoonAmber.Model;
using BoonAmber.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BoonAmber.Test.Model
{
    /// <summary>
    ///  Class for testing MAP
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MAPTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MAP
        //private MAP instance;

        public MAPTests()
        {
            // TODO uncomment below to create an instance of MAP
            //instance = new MAP();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MAP
        /// </summary>
        [Fact]
        public void MAPInstanceTest()
        {
            // TODO uncomment below to test "IsType" MAP
            //Assert.IsType<MAP>(instance);
        }


        /// <summary>
        /// Test the property 'VersionNumber'
        /// </summary>
        [Fact]
        public void VersionNumberTest()
        {
            // TODO unit test for the property 'VersionNumber'
        }
        /// <summary>
        /// Test the property 'MAutotuneRange'
        /// </summary>
        [Fact]
        public void MAutotuneRangeTest()
        {
            // TODO unit test for the property 'MAutotuneRange'
        }
        /// <summary>
        /// Test the property 'MAutotunePV'
        /// </summary>
        [Fact]
        public void MAutotunePVTest()
        {
            // TODO unit test for the property 'MAutotunePV'
        }
        /// <summary>
        /// Test the property 'MAutotuneByFeatures'
        /// </summary>
        [Fact]
        public void MAutotuneByFeaturesTest()
        {
            // TODO unit test for the property 'MAutotuneByFeatures'
        }
        /// <summary>
        /// Test the property 'MMaxClusters'
        /// </summary>
        [Fact]
        public void MMaxClustersTest()
        {
            // TODO unit test for the property 'MMaxClusters'
        }
        /// <summary>
        /// Test the property 'MFeaturesToTuneArray'
        /// </summary>
        [Fact]
        public void MFeaturesToTuneArrayTest()
        {
            // TODO unit test for the property 'MFeaturesToTuneArray'
        }

    }

}
