/*
 * Amber API Server
 *
 * Boon Logic Amber API Server
 *
 * The version of the OpenAPI document: 1.0.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BoonAmber.Api;
using BoonAmber.Model;
using BoonAmber.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BoonAmber.Test.Model
{
    /// <summary>
    ///  Class for testing MAutotune
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MAutotuneTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MAutotune
        //private MAutotune instance;

        public MAutotuneTests()
        {
            // TODO uncomment below to create an instance of MAutotune
            //instance = new MAutotune();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MAutotune
        /// </summary>
        [Fact]
        public void MAutotuneInstanceTest()
        {
            // TODO uncomment below to test "IsType" MAutotune
            //Assert.IsType<MAutotune>(instance);
        }


        /// <summary>
        /// Test the property 'VersionNumber'
        /// </summary>
        [Fact]
        public void VersionNumberTest()
        {
            // TODO unit test for the property 'VersionNumber'
        }
        /// <summary>
        /// Test the property 'MAutotuningInProgress'
        /// </summary>
        [Fact]
        public void MAutotuningInProgressTest()
        {
            // TODO unit test for the property 'MAutotuningInProgress'
        }
        /// <summary>
        /// Test the property 'MPercentComplete'
        /// </summary>
        [Fact]
        public void MPercentCompleteTest()
        {
            // TODO unit test for the property 'MPercentComplete'
        }
        /// <summary>
        /// Test the property 'MAutotuningSucceeded'
        /// </summary>
        [Fact]
        public void MAutotuningSucceededTest()
        {
            // TODO unit test for the property 'MAutotuningSucceeded'
        }
        /// <summary>
        /// Test the property 'MNumPatternsToAutotune'
        /// </summary>
        [Fact]
        public void MNumPatternsToAutotuneTest()
        {
            // TODO unit test for the property 'MNumPatternsToAutotune'
        }
        /// <summary>
        /// Test the property 'MErrorStringBuffer'
        /// </summary>
        [Fact]
        public void MErrorStringBufferTest()
        {
            // TODO unit test for the property 'MErrorStringBuffer'
        }
        /// <summary>
        /// Test the property 'MFeaturesToTuneArray'
        /// </summary>
        [Fact]
        public void MFeaturesToTuneArrayTest()
        {
            // TODO unit test for the property 'MFeaturesToTuneArray'
        }
        /// <summary>
        /// Test the property 'MNCP'
        /// </summary>
        [Fact]
        public void MNCPTest()
        {
            // TODO unit test for the property 'MNCP'
        }
        /// <summary>
        /// Test the property 'MAP'
        /// </summary>
        [Fact]
        public void MAPTest()
        {
            // TODO unit test for the property 'MAP'
        }

    }

}
