/*
 * Amber API Server
 *
 * Boon Logic Amber API Server
 *
 * The version of the OpenAPI document: 1.0.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BoonAmber.Api;
using BoonAmber.Model;
using BoonAmber.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BoonAmber.Test.Model
{
    /// <summary>
    ///  Class for testing MBufferStats
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MBufferStatsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MBufferStats
        //private MBufferStats instance;

        public MBufferStatsTests()
        {
            // TODO uncomment below to create an instance of MBufferStats
            //instance = new MBufferStats();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MBufferStats
        /// </summary>
        [Fact]
        public void MBufferStatsInstanceTest()
        {
            // TODO uncomment below to test "IsType" MBufferStats
            //Assert.IsType<MBufferStats>(instance);
        }


        /// <summary>
        /// Test the property 'VersionNumber'
        /// </summary>
        [Fact]
        public void VersionNumberTest()
        {
            // TODO unit test for the property 'VersionNumber'
        }
        /// <summary>
        /// Test the property 'TotalBytesWritten'
        /// </summary>
        [Fact]
        public void TotalBytesWrittenTest()
        {
            // TODO unit test for the property 'TotalBytesWritten'
        }
        /// <summary>
        /// Test the property 'TotalBytesProcessed'
        /// </summary>
        [Fact]
        public void TotalBytesProcessedTest()
        {
            // TODO unit test for the property 'TotalBytesProcessed'
        }
        /// <summary>
        /// Test the property 'LoadBufferLength'
        /// </summary>
        [Fact]
        public void LoadBufferLengthTest()
        {
            // TODO unit test for the property 'LoadBufferLength'
        }
        /// <summary>
        /// Test the property 'LoadBufferCapacity'
        /// </summary>
        [Fact]
        public void LoadBufferCapacityTest()
        {
            // TODO unit test for the property 'LoadBufferCapacity'
        }

    }

}
