/*
 * Amber API Server
 *
 * Boon Logic Amber API Server
 *
 * The version of the OpenAPI document: 1.0.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BoonAmber.Api;
using BoonAmber.Model;
using BoonAmber.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BoonAmber.Test.Model
{
    /// <summary>
    ///  Class for testing MNanoConfig
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MNanoConfigTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MNanoConfig
        //private MNanoConfig instance;

        public MNanoConfigTests()
        {
            // TODO uncomment below to create an instance of MNanoConfig
            //instance = new MNanoConfig();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MNanoConfig
        /// </summary>
        [Fact]
        public void MNanoConfigInstanceTest()
        {
            // TODO uncomment below to test "IsType" MNanoConfig
            //Assert.IsType<MNanoConfig>(instance);
        }


        /// <summary>
        /// Test the property 'VersionNumber'
        /// </summary>
        [Fact]
        public void VersionNumberTest()
        {
            // TODO unit test for the property 'VersionNumber'
        }
        /// <summary>
        /// Test the property 'MNumericFormat'
        /// </summary>
        [Fact]
        public void MNumericFormatTest()
        {
            // TODO unit test for the property 'MNumericFormat'
        }
        /// <summary>
        /// Test the property 'MAccuracy'
        /// </summary>
        [Fact]
        public void MAccuracyTest()
        {
            // TODO unit test for the property 'MAccuracy'
        }
        /// <summary>
        /// Test the property 'MPercentVariation'
        /// </summary>
        [Fact]
        public void MPercentVariationTest()
        {
            // TODO unit test for the property 'MPercentVariation'
        }
        /// <summary>
        /// Test the property 'NumOfFeatures'
        /// </summary>
        [Fact]
        public void NumOfFeaturesTest()
        {
            // TODO unit test for the property 'NumOfFeatures'
        }
        /// <summary>
        /// Test the property 'Features'
        /// </summary>
        [Fact]
        public void FeaturesTest()
        {
            // TODO unit test for the property 'Features'
        }

    }

}
