/* 
 * Amber API Server
 *
 * Boon Logic Amber API Server
 *
 * OpenAPI spec version: 1.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BoonAmber.Api;
using BoonAmber.Model;
using BoonAmber.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BoonAmber.Test
{
    /// <summary>
    ///  Class for testing MNanoConfig
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MNanoConfigTests
    {
        // TODO uncomment below to declare an instance variable for MNanoConfig
        //private MNanoConfig instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MNanoConfig
            //instance = new MNanoConfig();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MNanoConfig
        /// </summary>
        [Test]
        public void MNanoConfigInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MNanoConfig
            //Assert.IsInstanceOfType<MNanoConfig> (instance, "variable 'instance' is a MNanoConfig");
        }


        /// <summary>
        /// Test the property 'VersionNumber'
        /// </summary>
        [Test]
        public void VersionNumberTest()
        {
            // TODO unit test for the property 'VersionNumber'
        }
        /// <summary>
        /// Test the property 'MNumericFormat'
        /// </summary>
        [Test]
        public void MNumericFormatTest()
        {
            // TODO unit test for the property 'MNumericFormat'
        }
        /// <summary>
        /// Test the property 'MAccuracy'
        /// </summary>
        [Test]
        public void MAccuracyTest()
        {
            // TODO unit test for the property 'MAccuracy'
        }
        /// <summary>
        /// Test the property 'MPercentVariation'
        /// </summary>
        [Test]
        public void MPercentVariationTest()
        {
            // TODO unit test for the property 'MPercentVariation'
        }
        /// <summary>
        /// Test the property 'NumOfFeatures'
        /// </summary>
        [Test]
        public void NumOfFeaturesTest()
        {
            // TODO unit test for the property 'NumOfFeatures'
        }
        /// <summary>
        /// Test the property 'Features'
        /// </summary>
        [Test]
        public void FeaturesTest()
        {
            // TODO unit test for the property 'Features'
        }

    }

}
