/*
 * Amber API Server
 *
 * Boon Logic Amber API Server
 *
 * The version of the OpenAPI document: 1.0.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BoonAmber.Api;
using BoonAmber.Model;
using BoonAmber.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BoonAmber.Test.Model
{
    /// <summary>
    ///  Class for testing MNanoBackend
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MNanoBackendTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MNanoBackend
        //private MNanoBackend instance;

        public MNanoBackendTests()
        {
            // TODO uncomment below to create an instance of MNanoBackend
            //instance = new MNanoBackend();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MNanoBackend
        /// </summary>
        [Fact]
        public void MNanoBackendInstanceTest()
        {
            // TODO uncomment below to test "IsType" MNanoBackend
            //Assert.IsType<MNanoBackend>(instance);
        }


        /// <summary>
        /// Test the property 'VersionNumber'
        /// </summary>
        [Fact]
        public void VersionNumberTest()
        {
            // TODO unit test for the property 'VersionNumber'
        }
        /// <summary>
        /// Test the property 'MPatternMemory'
        /// </summary>
        [Fact]
        public void MPatternMemoryTest()
        {
            // TODO unit test for the property 'MPatternMemory'
        }
        /// <summary>
        /// Test the property 'MInitComplete'
        /// </summary>
        [Fact]
        public void MInitCompleteTest()
        {
            // TODO unit test for the property 'MInitComplete'
        }
        /// <summary>
        /// Test the property 'MPatternLength'
        /// </summary>
        [Fact]
        public void MPatternLengthTest()
        {
            // TODO unit test for the property 'MPatternLength'
        }
        /// <summary>
        /// Test the property 'MLearningIsOn'
        /// </summary>
        [Fact]
        public void MLearningIsOnTest()
        {
            // TODO unit test for the property 'MLearningIsOn'
        }
        /// <summary>
        /// Test the property 'MNumOfPatternsClustered'
        /// </summary>
        [Fact]
        public void MNumOfPatternsClusteredTest()
        {
            // TODO unit test for the property 'MNumOfPatternsClustered'
        }

    }

}
