/*
 * Amber API Server
 *
 * Boon Logic Amber API Server
 *
 * The version of the OpenAPI document: 1.0.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BoonAmber.Api;
using BoonAmber.Model;
using BoonAmber.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BoonAmber.Test.Model
{
    /// <summary>
    ///  Class for testing MPatternMemory
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MPatternMemoryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MPatternMemory
        //private MPatternMemory instance;

        public MPatternMemoryTests()
        {
            // TODO uncomment below to create an instance of MPatternMemory
            //instance = new MPatternMemory();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MPatternMemory
        /// </summary>
        [Fact]
        public void MPatternMemoryInstanceTest()
        {
            // TODO uncomment below to test "IsType" MPatternMemory
            //Assert.IsType<MPatternMemory>(instance);
        }


        /// <summary>
        /// Test the property 'VersionNumber'
        /// </summary>
        [Fact]
        public void VersionNumberTest()
        {
            // TODO unit test for the property 'VersionNumber'
        }

    }

}
