/*
 * Amber API Server
 *
 * Boon Logic Amber API Server
 *
 * The version of the OpenAPI document: 1.0.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BoonAmber.Api;
using BoonAmber.Model;
using BoonAmber.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BoonAmber.Test.Model
{
    /// <summary>
    ///  Class for testing MRecentAnalytics
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MRecentAnalyticsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for MRecentAnalytics
        //private MRecentAnalytics instance;

        public MRecentAnalyticsTests()
        {
            // TODO uncomment below to create an instance of MRecentAnalytics
            //instance = new MRecentAnalytics();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of MRecentAnalytics
        /// </summary>
        [Fact]
        public void MRecentAnalyticsInstanceTest()
        {
            // TODO uncomment below to test "IsType" MRecentAnalytics
            //Assert.IsType<MRecentAnalytics>(instance);
        }


        /// <summary>
        /// Test the property 'VersionNumber'
        /// </summary>
        [Fact]
        public void VersionNumberTest()
        {
            // TODO unit test for the property 'VersionNumber'
        }
        /// <summary>
        /// Test the property 'MValues'
        /// </summary>
        [Fact]
        public void MValuesTest()
        {
            // TODO unit test for the property 'MValues'
        }

    }

}
