/* 
 * Amber API Server
 *
 * Boon Logic Amber API Server
 *
 * OpenAPI spec version: 1.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BoonAmber.Api;
using BoonAmber.Model;
using BoonAmber.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BoonAmber.Test
{
    /// <summary>
    ///  Class for testing MRecentTimes
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MRecentTimesTests
    {
        // TODO uncomment below to declare an instance variable for MRecentTimes
        //private MRecentTimes instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MRecentTimes
            //instance = new MRecentTimes();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MRecentTimes
        /// </summary>
        [Test]
        public void MRecentTimesInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MRecentTimes
            //Assert.IsInstanceOfType<MRecentTimes> (instance, "variable 'instance' is a MRecentTimes");
        }


        /// <summary>
        /// Test the property 'VersionNumber'
        /// </summary>
        [Test]
        public void VersionNumberTest()
        {
            // TODO unit test for the property 'VersionNumber'
        }
        /// <summary>
        /// Test the property 'MValues'
        /// </summary>
        [Test]
        public void MValuesTest()
        {
            // TODO unit test for the property 'MValues'
        }

    }

}
