/* 
 * Amber API Server
 *
 * Boon Logic Amber API Server
 *
 * OpenAPI spec version: 1.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BoonAmber.Api;
using BoonAmber.Model;
using BoonAmber.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BoonAmber.Test
{
    /// <summary>
    ///  Class for testing PostPretrainRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PostPretrainRequestTests
    {
        // TODO uncomment below to declare an instance variable for PostPretrainRequest
        //private PostPretrainRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PostPretrainRequest
            //instance = new PostPretrainRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PostPretrainRequest
        /// </summary>
        [Test]
        public void PostPretrainRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PostPretrainRequest
            //Assert.IsInstanceOfType<PostPretrainRequest> (instance, "variable 'instance' is a PostPretrainRequest");
        }


        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Test]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }
        /// <summary>
        /// Test the property 'Format'
        /// </summary>
        [Test]
        public void FormatTest()
        {
            // TODO unit test for the property 'Format'
        }
        /// <summary>
        /// Test the property 'AutotuneConfig'
        /// </summary>
        [Test]
        public void AutotuneConfigTest()
        {
            // TODO unit test for the property 'AutotuneConfig'
        }

    }

}
