/* 
 * Amber API Server
 *
 * Boon Logic Amber API Server
 *
 * OpenAPI spec version: 1.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BoonAmber.Api;
using BoonAmber.Model;
using BoonAmber.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BoonAmber.Test
{
    /// <summary>
    ///  Class for testing PostConfigRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PostConfigRequestTests
    {
        // TODO uncomment below to declare an instance variable for PostConfigRequest
        //private PostConfigRequest instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PostConfigRequest
            //instance = new PostConfigRequest();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PostConfigRequest
        /// </summary>
        [Test]
        public void PostConfigRequestInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PostConfigRequest
            //Assert.IsInstanceOfType<PostConfigRequest> (instance, "variable 'instance' is a PostConfigRequest");
        }


        /// <summary>
        /// Test the property 'FeatureCount'
        /// </summary>
        [Test]
        public void FeatureCountTest()
        {
            // TODO unit test for the property 'FeatureCount'
        }
        /// <summary>
        /// Test the property 'StreamingWindowSize'
        /// </summary>
        [Test]
        public void StreamingWindowSizeTest()
        {
            // TODO unit test for the property 'StreamingWindowSize'
        }
        /// <summary>
        /// Test the property 'Features'
        /// </summary>
        [Test]
        public void FeaturesTest()
        {
            // TODO unit test for the property 'Features'
        }
        /// <summary>
        /// Test the property 'SamplesToBuffer'
        /// </summary>
        [Test]
        public void SamplesToBufferTest()
        {
            // TODO unit test for the property 'SamplesToBuffer'
        }
        /// <summary>
        /// Test the property 'PercentVariationOverride'
        /// </summary>
        [Test]
        public void PercentVariationOverrideTest()
        {
            // TODO unit test for the property 'PercentVariationOverride'
        }

    }

}
