/*
 * Amber API Server
 *
 * Boon Logic Amber API Server
 *
 * The version of the OpenAPI document: 1.0.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BoonAmber.Api;
using BoonAmber.Model;
using BoonAmber.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BoonAmber.Test.Model
{
    /// <summary>
    ///  Class for testing PostPretrainResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PostPretrainResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PostPretrainResponse
        //private PostPretrainResponse instance;

        public PostPretrainResponseTests()
        {
            // TODO uncomment below to create an instance of PostPretrainResponse
            //instance = new PostPretrainResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PostPretrainResponse
        /// </summary>
        [Fact]
        public void PostPretrainResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" PostPretrainResponse
            //Assert.IsType<PostPretrainResponse>(instance);
        }


        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'AmberTransaction'
        /// </summary>
        [Fact]
        public void AmberTransactionTest()
        {
            // TODO unit test for the property 'AmberTransaction'
        }
        /// <summary>
        /// Test the property 'AmberChunk'
        /// </summary>
        [Fact]
        public void AmberChunkTest()
        {
            // TODO unit test for the property 'AmberChunk'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

    }

}
