/* 
 * Amber API Server
 *
 * Boon Logic Amber API Server
 *
 * OpenAPI spec version: 1.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BoonAmber.Api;
using BoonAmber.Model;
using BoonAmber.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BoonAmber.Test
{
    /// <summary>
    ///  Class for testing PutConfigResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PutConfigResponseTests
    {
        // TODO uncomment below to declare an instance variable for PutConfigResponse
        //private PutConfigResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PutConfigResponse
            //instance = new PutConfigResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PutConfigResponse
        /// </summary>
        [Test]
        public void PutConfigResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PutConfigResponse
            //Assert.IsInstanceOfType<PutConfigResponse> (instance, "variable 'instance' is a PutConfigResponse");
        }


        /// <summary>
        /// Test the property 'Features'
        /// </summary>
        [Test]
        public void FeaturesTest()
        {
            // TODO unit test for the property 'Features'
        }
        /// <summary>
        /// Test the property 'Streaming'
        /// </summary>
        [Test]
        public void StreamingTest()
        {
            // TODO unit test for the property 'Streaming'
        }

    }

}
