/* 
 * Amber API Server
 *
 * Boon Logic Amber API Server
 *
 * OpenAPI spec version: 1.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BoonAmber.Api;
using BoonAmber.Model;
using BoonAmber.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BoonAmber.Test
{
    /// <summary>
    ///  Class for testing PutStreamFeature
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PutStreamFeatureTests
    {
        // TODO uncomment below to declare an instance variable for PutStreamFeature
        //private PutStreamFeature instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PutStreamFeature
            //instance = new PutStreamFeature();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PutStreamFeature
        /// </summary>
        [Test]
        public void PutStreamFeatureInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PutStreamFeature
            //Assert.IsInstanceOfType<PutStreamFeature> (instance, "variable 'instance' is a PutStreamFeature");
        }


        /// <summary>
        /// Test the property 'Label'
        /// </summary>
        [Test]
        public void LabelTest()
        {
            // TODO unit test for the property 'Label'
        }
        /// <summary>
        /// Test the property 'Value'
        /// </summary>
        [Test]
        public void ValueTest()
        {
            // TODO unit test for the property 'Value'
        }
        /// <summary>
        /// Test the property 'Ts'
        /// </summary>
        [Test]
        public void TsTest()
        {
            // TODO unit test for the property 'Ts'
        }

    }

}
