/* 
 * Amber API Server
 *
 * Boon Logic Amber API Server
 *
 * OpenAPI spec version: 1.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BoonAmber.Api;
using BoonAmber.Model;
using BoonAmber.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BoonAmber.Test
{
    /// <summary>
    ///  Class for testing SensorUsageInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SensorUsageInfoTests
    {
        // TODO uncomment below to declare an instance variable for SensorUsageInfo
        //private SensorUsageInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SensorUsageInfo
            //instance = new SensorUsageInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SensorUsageInfo
        /// </summary>
        [Test]
        public void SensorUsageInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SensorUsageInfo
            //Assert.IsInstanceOfType<SensorUsageInfo> (instance, "variable 'instance' is a SensorUsageInfo");
        }


        /// <summary>
        /// Test the property 'PostConfig'
        /// </summary>
        [Test]
        public void PostConfigTest()
        {
            // TODO unit test for the property 'PostConfig'
        }
        /// <summary>
        /// Test the property 'PostOutage'
        /// </summary>
        [Test]
        public void PostOutageTest()
        {
            // TODO unit test for the property 'PostOutage'
        }
        /// <summary>
        /// Test the property 'PostStream'
        /// </summary>
        [Test]
        public void PostStreamTest()
        {
            // TODO unit test for the property 'PostStream'
        }
        /// <summary>
        /// Test the property 'PutSensor'
        /// </summary>
        [Test]
        public void PutSensorTest()
        {
            // TODO unit test for the property 'PutSensor'
        }
        /// <summary>
        /// Test the property 'GetSensor'
        /// </summary>
        [Test]
        public void GetSensorTest()
        {
            // TODO unit test for the property 'GetSensor'
        }
        /// <summary>
        /// Test the property 'GetConfig'
        /// </summary>
        [Test]
        public void GetConfigTest()
        {
            // TODO unit test for the property 'GetConfig'
        }
        /// <summary>
        /// Test the property 'GetStatus'
        /// </summary>
        [Test]
        public void GetStatusTest()
        {
            // TODO unit test for the property 'GetStatus'
        }
        /// <summary>
        /// Test the property 'GetRootCause'
        /// </summary>
        [Test]
        public void GetRootCauseTest()
        {
            // TODO unit test for the property 'GetRootCause'
        }
        /// <summary>
        /// Test the property 'GetAmberSummary'
        /// </summary>
        [Test]
        public void GetAmberSummaryTest()
        {
            // TODO unit test for the property 'GetAmberSummary'
        }
        /// <summary>
        /// Test the property 'PostPretrain'
        /// </summary>
        [Test]
        public void PostPretrainTest()
        {
            // TODO unit test for the property 'PostPretrain'
        }
        /// <summary>
        /// Test the property 'GetPretrain'
        /// </summary>
        [Test]
        public void GetPretrainTest()
        {
            // TODO unit test for the property 'GetPretrain'
        }

    }

}
