/*
 * Amber API Server
 *
 * Boon Logic Amber API Server
 *
 * The version of the OpenAPI document: 1.0.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BoonAmber.Api;
using BoonAmber.Model;
using BoonAmber.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BoonAmber.Test.Model
{
    /// <summary>
    ///  Class for testing SensorInstance
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class SensorInstanceTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for SensorInstance
        //private SensorInstance instance;

        public SensorInstanceTests()
        {
            // TODO uncomment below to create an instance of SensorInstance
            //instance = new SensorInstance();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of SensorInstance
        /// </summary>
        [Fact]
        public void SensorInstanceInstanceTest()
        {
            // TODO uncomment below to test "IsType" SensorInstance
            //Assert.IsType<SensorInstance>(instance);
        }


        /// <summary>
        /// Test the property 'Label'
        /// </summary>
        [Fact]
        public void LabelTest()
        {
            // TODO unit test for the property 'Label'
        }
        /// <summary>
        /// Test the property 'SensorId'
        /// </summary>
        [Fact]
        public void SensorIdTest()
        {
            // TODO unit test for the property 'SensorId'
        }

    }

}
