/*
 * Amber API Server
 *
 * Boon Logic Amber API Server
 *
 * The version of the OpenAPI document: 1.0.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BoonAmber.Api;
using BoonAmber.Model;
using BoonAmber.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BoonAmber.Test.Model
{
    /// <summary>
    ///  Class for testing Uint64Array
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class Uint64ArrayTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Uint64Array
        //private Uint64Array instance;

        public Uint64ArrayTests()
        {
            // TODO uncomment below to create an instance of Uint64Array
            //instance = new Uint64Array();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Uint64Array
        /// </summary>
        [Fact]
        public void Uint64ArrayInstanceTest()
        {
            // TODO uncomment below to test "IsType" Uint64Array
            //Assert.IsType<Uint64Array>(instance);
        }



    }

}
