/*
 * Amber API Server
 *
 * Boon Logic Amber API Server
 *
 * The version of the OpenAPI document: 1.0.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = BoonAmber.Client.OpenAPIDateConverter;

namespace BoonAmber.Model
{
    /// <summary>
    /// PutStreamResponse
    /// </summary>
    [DataContract(Name = "putStreamResponse")]
    public partial class PutStreamResponse : IEquatable<PutStreamResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="PutStreamResponse" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected PutStreamResponse() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="PutStreamResponse" /> class.
        /// </summary>
        /// <param name="vector">updated sensor fusion vector as a string of comma-separated values (required).</param>
        /// <param name="results">results.</param>
        public PutStreamResponse(string vector = default(string), PostStreamResponse results = default(PostStreamResponse))
        {
            // to ensure "vector" is required (not null)
            if (vector == null)
            {
                throw new ArgumentNullException("vector is a required property for PutStreamResponse and cannot be null");
            }
            this.Vector = vector;
            this.Results = results;
        }

        /// <summary>
        /// updated sensor fusion vector as a string of comma-separated values
        /// </summary>
        /// <value>updated sensor fusion vector as a string of comma-separated values</value>
        [DataMember(Name = "vector", IsRequired = true, EmitDefaultValue = false)]
        public string Vector { get; set; }

        /// <summary>
        /// Gets or Sets Results
        /// </summary>
        [DataMember(Name = "results", EmitDefaultValue = false)]
        public PostStreamResponse Results { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class PutStreamResponse {\n");
            sb.Append("  Vector: ").Append(Vector).Append("\n");
            sb.Append("  Results: ").Append(Results).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as PutStreamResponse);
        }

        /// <summary>
        /// Returns true if PutStreamResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of PutStreamResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(PutStreamResponse input)
        {
            if (input == null)
            {
                return false;
            }
            return
                (
                    this.Vector == input.Vector ||
                    (this.Vector != null &&
                    this.Vector.Equals(input.Vector))
                ) &&
                (
                    this.Results == input.Results ||
                    (this.Results != null &&
                    this.Results.Equals(input.Results))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Vector != null)
                {
                    hashCode = (hashCode * 59) + this.Vector.GetHashCode();
                }
                if (this.Results != null)
                {
                    hashCode = (hashCode * 59) + this.Results.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
