/* 
 * Amber API Server
 *
 * Boon Logic Amber API Server
 *
 * OpenAPI spec version: 1.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using SwaggerDateConverter = BoonAmber.Client.SwaggerDateConverter;

namespace BoonAmber.Model
{
    /// <summary>
    /// StreamingEndpointUsageInfo
    /// </summary>
    [DataContract]
        public partial class StreamingEndpointUsageInfo :  IEquatable<StreamingEndpointUsageInfo>
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="StreamingEndpointUsageInfo" /> class.
        /// </summary>
        /// <param name="callsTotal">total number of calls to this endpoint (required).</param>
        /// <param name="callsThisPeriod">number of calls to this endpoint during the current billing period (required).</param>
        /// <param name="samplesTotal">total number of samples processed (required).</param>
        /// <param name="samplesThisPeriod">number of samples processed during the current billing period (required).</param>
        /// <param name="lastCalled">ISO formatted time of last call to this endpoint (required).</param>
        public StreamingEndpointUsageInfo(decimal? callsTotal = default(decimal?), decimal? callsThisPeriod = default(decimal?), decimal? samplesTotal = default(decimal?), decimal? samplesThisPeriod = default(decimal?), string lastCalled = default(string))
        {
            // to ensure "callsTotal" is required (not null)
            if (callsTotal == null)
            {
                throw new InvalidDataException("callsTotal is a required property for StreamingEndpointUsageInfo and cannot be null");
            }
            else
            {
                this.CallsTotal = callsTotal;
            }
            // to ensure "callsThisPeriod" is required (not null)
            if (callsThisPeriod == null)
            {
                throw new InvalidDataException("callsThisPeriod is a required property for StreamingEndpointUsageInfo and cannot be null");
            }
            else
            {
                this.CallsThisPeriod = callsThisPeriod;
            }
            // to ensure "samplesTotal" is required (not null)
            if (samplesTotal == null)
            {
                throw new InvalidDataException("samplesTotal is a required property for StreamingEndpointUsageInfo and cannot be null");
            }
            else
            {
                this.SamplesTotal = samplesTotal;
            }
            // to ensure "samplesThisPeriod" is required (not null)
            if (samplesThisPeriod == null)
            {
                throw new InvalidDataException("samplesThisPeriod is a required property for StreamingEndpointUsageInfo and cannot be null");
            }
            else
            {
                this.SamplesThisPeriod = samplesThisPeriod;
            }
            // to ensure "lastCalled" is required (not null)
            if (lastCalled == null)
            {
                throw new InvalidDataException("lastCalled is a required property for StreamingEndpointUsageInfo and cannot be null");
            }
            else
            {
                this.LastCalled = lastCalled;
            }
        }
        
        /// <summary>
        /// total number of calls to this endpoint
        /// </summary>
        /// <value>total number of calls to this endpoint</value>
        [DataMember(Name="callsTotal", EmitDefaultValue=false)]
        public decimal? CallsTotal { get; set; }

        /// <summary>
        /// number of calls to this endpoint during the current billing period
        /// </summary>
        /// <value>number of calls to this endpoint during the current billing period</value>
        [DataMember(Name="callsThisPeriod", EmitDefaultValue=false)]
        public decimal? CallsThisPeriod { get; set; }

        /// <summary>
        /// total number of samples processed
        /// </summary>
        /// <value>total number of samples processed</value>
        [DataMember(Name="samplesTotal", EmitDefaultValue=false)]
        public decimal? SamplesTotal { get; set; }

        /// <summary>
        /// number of samples processed during the current billing period
        /// </summary>
        /// <value>number of samples processed during the current billing period</value>
        [DataMember(Name="samplesThisPeriod", EmitDefaultValue=false)]
        public decimal? SamplesThisPeriod { get; set; }

        /// <summary>
        /// ISO formatted time of last call to this endpoint
        /// </summary>
        /// <value>ISO formatted time of last call to this endpoint</value>
        [DataMember(Name="lastCalled", EmitDefaultValue=false)]
        public string LastCalled { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class StreamingEndpointUsageInfo {\n");
            sb.Append("  CallsTotal: ").Append(CallsTotal).Append("\n");
            sb.Append("  CallsThisPeriod: ").Append(CallsThisPeriod).Append("\n");
            sb.Append("  SamplesTotal: ").Append(SamplesTotal).Append("\n");
            sb.Append("  SamplesThisPeriod: ").Append(SamplesThisPeriod).Append("\n");
            sb.Append("  LastCalled: ").Append(LastCalled).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as StreamingEndpointUsageInfo);
        }

        /// <summary>
        /// Returns true if StreamingEndpointUsageInfo instances are equal
        /// </summary>
        /// <param name="input">Instance of StreamingEndpointUsageInfo to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(StreamingEndpointUsageInfo input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.CallsTotal == input.CallsTotal ||
                    (this.CallsTotal != null &&
                    this.CallsTotal.Equals(input.CallsTotal))
                ) && 
                (
                    this.CallsThisPeriod == input.CallsThisPeriod ||
                    (this.CallsThisPeriod != null &&
                    this.CallsThisPeriod.Equals(input.CallsThisPeriod))
                ) && 
                (
                    this.SamplesTotal == input.SamplesTotal ||
                    (this.SamplesTotal != null &&
                    this.SamplesTotal.Equals(input.SamplesTotal))
                ) && 
                (
                    this.SamplesThisPeriod == input.SamplesThisPeriod ||
                    (this.SamplesThisPeriod != null &&
                    this.SamplesThisPeriod.Equals(input.SamplesThisPeriod))
                ) && 
                (
                    this.LastCalled == input.LastCalled ||
                    (this.LastCalled != null &&
                    this.LastCalled.Equals(input.LastCalled))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.CallsTotal != null)
                    hashCode = hashCode * 59 + this.CallsTotal.GetHashCode();
                if (this.CallsThisPeriod != null)
                    hashCode = hashCode * 59 + this.CallsThisPeriod.GetHashCode();
                if (this.SamplesTotal != null)
                    hashCode = hashCode * 59 + this.SamplesTotal.GetHashCode();
                if (this.SamplesThisPeriod != null)
                    hashCode = hashCode * 59 + this.SamplesThisPeriod.GetHashCode();
                if (this.LastCalled != null)
                    hashCode = hashCode * 59 + this.LastCalled.GetHashCode();
                return hashCode;
            }
        }
    }
}
