/*
 * Amber API Server
 *
 * Boon Logic Amber API Server
 *
 * The version of the OpenAPI document: 1.0.3
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = BoonAmber.Client.OpenAPIDateConverter;

namespace BoonAmber.Model
{
    /// <summary>
    /// StreamingEndpointUsageInfo
    /// </summary>
    [DataContract(Name = "streamingEndpointUsageInfo")]
    public partial class StreamingEndpointUsageInfo : IEquatable<StreamingEndpointUsageInfo>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="StreamingEndpointUsageInfo" /> class.
        /// </summary>
        [JsonConstructorAttribute]
        protected StreamingEndpointUsageInfo() { }
        /// <summary>
        /// Initializes a new instance of the <see cref="StreamingEndpointUsageInfo" /> class.
        /// </summary>
        /// <param name="callsTotal">total number of calls to this endpoint (required).</param>
        /// <param name="callsThisPeriod">number of calls to this endpoint during the current billing period (required).</param>
        /// <param name="samplesTotal">total number of samples processed (required).</param>
        /// <param name="samplesThisPeriod">number of samples processed during the current billing period (required).</param>
        /// <param name="lastCalled">ISO formatted time of last call to this endpoint (required).</param>
        public StreamingEndpointUsageInfo(int callsTotal = default(int), int callsThisPeriod = default(int), int samplesTotal = default(int), int samplesThisPeriod = default(int), string lastCalled = default(string))
        {
            this.CallsTotal = callsTotal;
            this.CallsThisPeriod = callsThisPeriod;
            this.SamplesTotal = samplesTotal;
            this.SamplesThisPeriod = samplesThisPeriod;
            // to ensure "lastCalled" is required (not null)
            if (lastCalled == null)
            {
                throw new ArgumentNullException("lastCalled is a required property for StreamingEndpointUsageInfo and cannot be null");
            }
            this.LastCalled = lastCalled;
        }

        /// <summary>
        /// total number of calls to this endpoint
        /// </summary>
        /// <value>total number of calls to this endpoint</value>
        [DataMember(Name = "callsTotal", IsRequired = true, EmitDefaultValue = false)]
        public int CallsTotal { get; set; }

        /// <summary>
        /// number of calls to this endpoint during the current billing period
        /// </summary>
        /// <value>number of calls to this endpoint during the current billing period</value>
        [DataMember(Name = "callsThisPeriod", IsRequired = true, EmitDefaultValue = false)]
        public int CallsThisPeriod { get; set; }

        /// <summary>
        /// total number of samples processed
        /// </summary>
        /// <value>total number of samples processed</value>
        [DataMember(Name = "samplesTotal", IsRequired = true, EmitDefaultValue = false)]
        public int SamplesTotal { get; set; }

        /// <summary>
        /// number of samples processed during the current billing period
        /// </summary>
        /// <value>number of samples processed during the current billing period</value>
        [DataMember(Name = "samplesThisPeriod", IsRequired = true, EmitDefaultValue = false)]
        public int SamplesThisPeriod { get; set; }

        /// <summary>
        /// ISO formatted time of last call to this endpoint
        /// </summary>
        /// <value>ISO formatted time of last call to this endpoint</value>
        [DataMember(Name = "lastCalled", IsRequired = true, EmitDefaultValue = false)]
        public string LastCalled { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class StreamingEndpointUsageInfo {\n");
            sb.Append("  CallsTotal: ").Append(CallsTotal).Append("\n");
            sb.Append("  CallsThisPeriod: ").Append(CallsThisPeriod).Append("\n");
            sb.Append("  SamplesTotal: ").Append(SamplesTotal).Append("\n");
            sb.Append("  SamplesThisPeriod: ").Append(SamplesThisPeriod).Append("\n");
            sb.Append("  LastCalled: ").Append(LastCalled).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as StreamingEndpointUsageInfo);
        }

        /// <summary>
        /// Returns true if StreamingEndpointUsageInfo instances are equal
        /// </summary>
        /// <param name="input">Instance of StreamingEndpointUsageInfo to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(StreamingEndpointUsageInfo input)
        {
            if (input == null)
            {
                return false;
            }
            return 
                (
                    this.CallsTotal == input.CallsTotal ||
                    this.CallsTotal.Equals(input.CallsTotal)
                ) && 
                (
                    this.CallsThisPeriod == input.CallsThisPeriod ||
                    this.CallsThisPeriod.Equals(input.CallsThisPeriod)
                ) && 
                (
                    this.SamplesTotal == input.SamplesTotal ||
                    this.SamplesTotal.Equals(input.SamplesTotal)
                ) && 
                (
                    this.SamplesThisPeriod == input.SamplesThisPeriod ||
                    this.SamplesThisPeriod.Equals(input.SamplesThisPeriod)
                ) && 
                (
                    this.LastCalled == input.LastCalled ||
                    (this.LastCalled != null &&
                    this.LastCalled.Equals(input.LastCalled))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                hashCode = (hashCode * 59) + this.CallsTotal.GetHashCode();
                hashCode = (hashCode * 59) + this.CallsThisPeriod.GetHashCode();
                hashCode = (hashCode * 59) + this.SamplesTotal.GetHashCode();
                hashCode = (hashCode * 59) + this.SamplesThisPeriod.GetHashCode();
                if (this.LastCalled != null)
                {
                    hashCode = (hashCode * 59) + this.LastCalled.GetHashCode();
                }
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        public IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
