/* 
 * Amber API Server
 *
 * Boon Logic Amber API Server
 *
 * OpenAPI spec version: 1.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */
using System;
using System.Linq;
using System.IO;
using System.Text;
using System.Text.RegularExpressions;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;
using SwaggerDateConverter = BoonAmber.Client.SwaggerDateConverter;

namespace BoonAmber.Model
{
    /// <summary>
    /// GetStatusResponse
    /// </summary>
    [DataContract]
        public partial class GetStatusResponse :  IEquatable<GetStatusResponse>, IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="GetStatusResponse" /> class.
        /// </summary>
        /// <param name="pca">pca (required).</param>
        /// <param name="clusterGrowth">clusterGrowth (required).</param>
        /// <param name="clusterSizes">clusterSizes (required).</param>
        /// <param name="anomalyIndexes">anomalyIndexes (required).</param>
        /// <param name="frequencyIndexes">frequencyIndexes (required).</param>
        /// <param name="distanceIndexes">distanceIndexes (required).</param>
        /// <param name="totalInferences">inferences since the most recent restart (required).</param>
        /// <param name="numClusters">numClusters (required).</param>
        /// <param name="anomalyThreshold">anomalyThreshold (required).</param>
        /// <param name="state">state of the sensor. Possible state variables are: Error, Buffering, Autotuning, Learning, Monitoring (required).</param>
        public GetStatusResponse(PCA pca = default(PCA), Uint64Array clusterGrowth = default(Uint64Array), Uint64Array clusterSizes = default(Uint64Array), Uint16Array anomalyIndexes = default(Uint16Array), Uint16Array frequencyIndexes = default(Uint16Array), Uint16Array distanceIndexes = default(Uint16Array), int? totalInferences = default(int?), int? numClusters = default(int?), int? anomalyThreshold = default(int?), string state = default(string))
        {
            // to ensure "pca" is required (not null)
            if (pca == null)
            {
                throw new InvalidDataException("pca is a required property for GetStatusResponse and cannot be null");
            }
            else
            {
                this.Pca = pca;
            }
            // to ensure "clusterGrowth" is required (not null)
            if (clusterGrowth == null)
            {
                throw new InvalidDataException("clusterGrowth is a required property for GetStatusResponse and cannot be null");
            }
            else
            {
                this.ClusterGrowth = clusterGrowth;
            }
            // to ensure "clusterSizes" is required (not null)
            if (clusterSizes == null)
            {
                throw new InvalidDataException("clusterSizes is a required property for GetStatusResponse and cannot be null");
            }
            else
            {
                this.ClusterSizes = clusterSizes;
            }
            // to ensure "anomalyIndexes" is required (not null)
            if (anomalyIndexes == null)
            {
                throw new InvalidDataException("anomalyIndexes is a required property for GetStatusResponse and cannot be null");
            }
            else
            {
                this.AnomalyIndexes = anomalyIndexes;
            }
            // to ensure "frequencyIndexes" is required (not null)
            if (frequencyIndexes == null)
            {
                throw new InvalidDataException("frequencyIndexes is a required property for GetStatusResponse and cannot be null");
            }
            else
            {
                this.FrequencyIndexes = frequencyIndexes;
            }
            // to ensure "distanceIndexes" is required (not null)
            if (distanceIndexes == null)
            {
                throw new InvalidDataException("distanceIndexes is a required property for GetStatusResponse and cannot be null");
            }
            else
            {
                this.DistanceIndexes = distanceIndexes;
            }
            // to ensure "totalInferences" is required (not null)
            if (totalInferences == null)
            {
                throw new InvalidDataException("totalInferences is a required property for GetStatusResponse and cannot be null");
            }
            else
            {
                this.TotalInferences = totalInferences;
            }
            // to ensure "numClusters" is required (not null)
            if (numClusters == null)
            {
                throw new InvalidDataException("numClusters is a required property for GetStatusResponse and cannot be null");
            }
            else
            {
                this.NumClusters = numClusters;
            }
            // to ensure "anomalyThreshold" is required (not null)
            if (anomalyThreshold == null)
            {
                throw new InvalidDataException("anomalyThreshold is a required property for GetStatusResponse and cannot be null");
            }
            else
            {
                this.AnomalyThreshold = anomalyThreshold;
            }
            // to ensure "state" is required (not null)
            if (state == null)
            {
                throw new InvalidDataException("state is a required property for GetStatusResponse and cannot be null");
            }
            else
            {
                this.State = state;
            }
        }
        
        /// <summary>
        /// Gets or Sets Pca
        /// </summary>
        [DataMember(Name="pca", EmitDefaultValue=false)]
        public PCA Pca { get; set; }

        /// <summary>
        /// Gets or Sets ClusterGrowth
        /// </summary>
        [DataMember(Name="clusterGrowth", EmitDefaultValue=false)]
        public Uint64Array ClusterGrowth { get; set; }

        /// <summary>
        /// Gets or Sets ClusterSizes
        /// </summary>
        [DataMember(Name="clusterSizes", EmitDefaultValue=false)]
        public Uint64Array ClusterSizes { get; set; }

        /// <summary>
        /// Gets or Sets AnomalyIndexes
        /// </summary>
        [DataMember(Name="anomalyIndexes", EmitDefaultValue=false)]
        public Uint16Array AnomalyIndexes { get; set; }

        /// <summary>
        /// Gets or Sets FrequencyIndexes
        /// </summary>
        [DataMember(Name="frequencyIndexes", EmitDefaultValue=false)]
        public Uint16Array FrequencyIndexes { get; set; }

        /// <summary>
        /// Gets or Sets DistanceIndexes
        /// </summary>
        [DataMember(Name="distanceIndexes", EmitDefaultValue=false)]
        public Uint16Array DistanceIndexes { get; set; }

        /// <summary>
        /// inferences since the most recent restart
        /// </summary>
        /// <value>inferences since the most recent restart</value>
        [DataMember(Name="totalInferences", EmitDefaultValue=false)]
        public int? TotalInferences { get; set; }

        /// <summary>
        /// Gets or Sets NumClusters
        /// </summary>
        [DataMember(Name="numClusters", EmitDefaultValue=false)]
        public int? NumClusters { get; set; }

        /// <summary>
        /// Gets or Sets AnomalyThreshold
        /// </summary>
        [DataMember(Name="anomalyThreshold", EmitDefaultValue=false)]
        public int? AnomalyThreshold { get; set; }

        /// <summary>
        /// state of the sensor. Possible state variables are: Error, Buffering, Autotuning, Learning, Monitoring
        /// </summary>
        /// <value>state of the sensor. Possible state variables are: Error, Buffering, Autotuning, Learning, Monitoring</value>
        [DataMember(Name="state", EmitDefaultValue=false)]
        public string State { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class GetStatusResponse {\n");
            sb.Append("  Pca: ").Append(Pca).Append("\n");
            sb.Append("  ClusterGrowth: ").Append(ClusterGrowth).Append("\n");
            sb.Append("  ClusterSizes: ").Append(ClusterSizes).Append("\n");
            sb.Append("  AnomalyIndexes: ").Append(AnomalyIndexes).Append("\n");
            sb.Append("  FrequencyIndexes: ").Append(FrequencyIndexes).Append("\n");
            sb.Append("  DistanceIndexes: ").Append(DistanceIndexes).Append("\n");
            sb.Append("  TotalInferences: ").Append(TotalInferences).Append("\n");
            sb.Append("  NumClusters: ").Append(NumClusters).Append("\n");
            sb.Append("  AnomalyThreshold: ").Append(AnomalyThreshold).Append("\n");
            sb.Append("  State: ").Append(State).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }
  
        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="input">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object input)
        {
            return this.Equals(input as GetStatusResponse);
        }

        /// <summary>
        /// Returns true if GetStatusResponse instances are equal
        /// </summary>
        /// <param name="input">Instance of GetStatusResponse to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(GetStatusResponse input)
        {
            if (input == null)
                return false;

            return 
                (
                    this.Pca == input.Pca ||
                    (this.Pca != null &&
                    this.Pca.Equals(input.Pca))
                ) && 
                (
                    this.ClusterGrowth == input.ClusterGrowth ||
                    (this.ClusterGrowth != null &&
                    this.ClusterGrowth.Equals(input.ClusterGrowth))
                ) && 
                (
                    this.ClusterSizes == input.ClusterSizes ||
                    (this.ClusterSizes != null &&
                    this.ClusterSizes.Equals(input.ClusterSizes))
                ) && 
                (
                    this.AnomalyIndexes == input.AnomalyIndexes ||
                    (this.AnomalyIndexes != null &&
                    this.AnomalyIndexes.Equals(input.AnomalyIndexes))
                ) && 
                (
                    this.FrequencyIndexes == input.FrequencyIndexes ||
                    (this.FrequencyIndexes != null &&
                    this.FrequencyIndexes.Equals(input.FrequencyIndexes))
                ) && 
                (
                    this.DistanceIndexes == input.DistanceIndexes ||
                    (this.DistanceIndexes != null &&
                    this.DistanceIndexes.Equals(input.DistanceIndexes))
                ) && 
                (
                    this.TotalInferences == input.TotalInferences ||
                    (this.TotalInferences != null &&
                    this.TotalInferences.Equals(input.TotalInferences))
                ) && 
                (
                    this.NumClusters == input.NumClusters ||
                    (this.NumClusters != null &&
                    this.NumClusters.Equals(input.NumClusters))
                ) && 
                (
                    this.AnomalyThreshold == input.AnomalyThreshold ||
                    (this.AnomalyThreshold != null &&
                    this.AnomalyThreshold.Equals(input.AnomalyThreshold))
                ) && 
                (
                    this.State == input.State ||
                    (this.State != null &&
                    this.State.Equals(input.State))
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                int hashCode = 41;
                if (this.Pca != null)
                    hashCode = hashCode * 59 + this.Pca.GetHashCode();
                if (this.ClusterGrowth != null)
                    hashCode = hashCode * 59 + this.ClusterGrowth.GetHashCode();
                if (this.ClusterSizes != null)
                    hashCode = hashCode * 59 + this.ClusterSizes.GetHashCode();
                if (this.AnomalyIndexes != null)
                    hashCode = hashCode * 59 + this.AnomalyIndexes.GetHashCode();
                if (this.FrequencyIndexes != null)
                    hashCode = hashCode * 59 + this.FrequencyIndexes.GetHashCode();
                if (this.DistanceIndexes != null)
                    hashCode = hashCode * 59 + this.DistanceIndexes.GetHashCode();
                if (this.TotalInferences != null)
                    hashCode = hashCode * 59 + this.TotalInferences.GetHashCode();
                if (this.NumClusters != null)
                    hashCode = hashCode * 59 + this.NumClusters.GetHashCode();
                if (this.AnomalyThreshold != null)
                    hashCode = hashCode * 59 + this.AnomalyThreshold.GetHashCode();
                if (this.State != null)
                    hashCode = hashCode * 59 + this.State.GetHashCode();
                return hashCode;
            }
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }
}
