/* 
 * Amber API Server
 *
 * Boon Logic Amber API Server
 *
 * OpenAPI spec version: 1.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BoonAmber.Api;
using BoonAmber.Model;
using BoonAmber.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BoonAmber.Test
{
    /// <summary>
    ///  Class for testing FusionConfig
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class FusionConfigTests
    {
        // TODO uncomment below to declare an instance variable for FusionConfig
        //private FusionConfig instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of FusionConfig
            //instance = new FusionConfig();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of FusionConfig
        /// </summary>
        [Test]
        public void FusionConfigInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" FusionConfig
            //Assert.IsInstanceOfType<FusionConfig> (instance, "variable 'instance' is a FusionConfig");
        }


        /// <summary>
        /// Test the property 'Label'
        /// </summary>
        [Test]
        public void LabelTest()
        {
            // TODO unit test for the property 'Label'
        }
        /// <summary>
        /// Test the property 'SubmitRule'
        /// </summary>
        [Test]
        public void SubmitRuleTest()
        {
            // TODO unit test for the property 'SubmitRule'
        }

    }

}
