/* 
 * Amber API Server
 *
 * Boon Logic Amber API Server
 *
 * OpenAPI spec version: 1.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BoonAmber.Api;
using BoonAmber.Model;
using BoonAmber.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BoonAmber.Test
{
    /// <summary>
    ///  Class for testing GetSensorsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class GetSensorsResponseTests
    {
        // TODO uncomment below to declare an instance variable for GetSensorsResponse
        //private GetSensorsResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of GetSensorsResponse
            //instance = new GetSensorsResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of GetSensorsResponse
        /// </summary>
        [Test]
        public void GetSensorsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" GetSensorsResponse
            //Assert.IsInstanceOfType<GetSensorsResponse> (instance, "variable 'instance' is a GetSensorsResponse");
        }



    }

}
