/* 
 * Amber API Server
 *
 * Boon Logic Amber API Server
 *
 * OpenAPI spec version: 1.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BoonAmber.Api;
using BoonAmber.Model;
using BoonAmber.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BoonAmber.Test
{
    /// <summary>
    ///  Class for testing MAP
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class MAPTests
    {
        // TODO uncomment below to declare an instance variable for MAP
        //private MAP instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of MAP
            //instance = new MAP();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of MAP
        /// </summary>
        [Test]
        public void MAPInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" MAP
            //Assert.IsInstanceOfType<MAP> (instance, "variable 'instance' is a MAP");
        }


        /// <summary>
        /// Test the property 'VersionNumber'
        /// </summary>
        [Test]
        public void VersionNumberTest()
        {
            // TODO unit test for the property 'VersionNumber'
        }
        /// <summary>
        /// Test the property 'MAutotuneRange'
        /// </summary>
        [Test]
        public void MAutotuneRangeTest()
        {
            // TODO unit test for the property 'MAutotuneRange'
        }
        /// <summary>
        /// Test the property 'MAutotunePV'
        /// </summary>
        [Test]
        public void MAutotunePVTest()
        {
            // TODO unit test for the property 'MAutotunePV'
        }
        /// <summary>
        /// Test the property 'MAutotuneByFeatures'
        /// </summary>
        [Test]
        public void MAutotuneByFeaturesTest()
        {
            // TODO unit test for the property 'MAutotuneByFeatures'
        }
        /// <summary>
        /// Test the property 'MMaxClusters'
        /// </summary>
        [Test]
        public void MMaxClustersTest()
        {
            // TODO unit test for the property 'MMaxClusters'
        }
        /// <summary>
        /// Test the property 'MFeaturesToTuneArray'
        /// </summary>
        [Test]
        public void MFeaturesToTuneArrayTest()
        {
            // TODO unit test for the property 'MFeaturesToTuneArray'
        }

    }

}
