/* 
 * Amber API Server
 *
 * Boon Logic Amber API Server
 *
 * OpenAPI spec version: 1.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BoonAmber.Api;
using BoonAmber.Model;
using BoonAmber.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BoonAmber.Test
{
    /// <summary>
    ///  Class for testing PostPretrainResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PostPretrainResponseTests
    {
        // TODO uncomment below to declare an instance variable for PostPretrainResponse
        //private PostPretrainResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PostPretrainResponse
            //instance = new PostPretrainResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PostPretrainResponse
        /// </summary>
        [Test]
        public void PostPretrainResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PostPretrainResponse
            //Assert.IsInstanceOfType<PostPretrainResponse> (instance, "variable 'instance' is a PostPretrainResponse");
        }


        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Test]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }
        /// <summary>
        /// Test the property 'AmberTransaction'
        /// </summary>
        [Test]
        public void AmberTransactionTest()
        {
            // TODO unit test for the property 'AmberTransaction'
        }
        /// <summary>
        /// Test the property 'AmberChunk'
        /// </summary>
        [Test]
        public void AmberChunkTest()
        {
            // TODO unit test for the property 'AmberChunk'
        }
        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Test]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

    }

}
