/* 
 * Amber API Server
 *
 * Boon Logic Amber API Server
 *
 * OpenAPI spec version: 1.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BoonAmber.Api;
using BoonAmber.Model;
using BoonAmber.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BoonAmber.Test
{
    /// <summary>
    ///  Class for testing PostOutageResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PostOutageResponseTests
    {
        // TODO uncomment below to declare an instance variable for PostOutageResponse
        //private PostOutageResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PostOutageResponse
            //instance = new PostOutageResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PostOutageResponse
        /// </summary>
        [Test]
        public void PostOutageResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PostOutageResponse
            //Assert.IsInstanceOfType<PostOutageResponse> (instance, "variable 'instance' is a PostOutageResponse");
        }



    }

}
