/* 
 * Amber API Server
 *
 * Boon Logic Amber API Server
 *
 * OpenAPI spec version: 1.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BoonAmber.Api;
using BoonAmber.Model;
using BoonAmber.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BoonAmber.Test
{
    /// <summary>
    ///  Class for testing PutStreamResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class PutStreamResponseTests
    {
        // TODO uncomment below to declare an instance variable for PutStreamResponse
        //private PutStreamResponse instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of PutStreamResponse
            //instance = new PutStreamResponse();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of PutStreamResponse
        /// </summary>
        [Test]
        public void PutStreamResponseInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" PutStreamResponse
            //Assert.IsInstanceOfType<PutStreamResponse> (instance, "variable 'instance' is a PutStreamResponse");
        }


        /// <summary>
        /// Test the property 'Vector'
        /// </summary>
        [Test]
        public void VectorTest()
        {
            // TODO unit test for the property 'Vector'
        }
        /// <summary>
        /// Test the property 'Results'
        /// </summary>
        [Test]
        public void ResultsTest()
        {
            // TODO unit test for the property 'Results'
        }

    }

}
