/* 
 * Amber API Server
 *
 * Boon Logic Amber API Server
 *
 * OpenAPI spec version: 1.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BoonAmber.Api;
using BoonAmber.Model;
using BoonAmber.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BoonAmber.Test
{
    /// <summary>
    ///  Class for testing SensorInstance
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class SensorInstanceTests
    {
        // TODO uncomment below to declare an instance variable for SensorInstance
        //private SensorInstance instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of SensorInstance
            //instance = new SensorInstance();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of SensorInstance
        /// </summary>
        [Test]
        public void SensorInstanceInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" SensorInstance
            //Assert.IsInstanceOfType<SensorInstance> (instance, "variable 'instance' is a SensorInstance");
        }


        /// <summary>
        /// Test the property 'Label'
        /// </summary>
        [Test]
        public void LabelTest()
        {
            // TODO unit test for the property 'Label'
        }
        /// <summary>
        /// Test the property 'SensorId'
        /// </summary>
        [Test]
        public void SensorIdTest()
        {
            // TODO unit test for the property 'SensorId'
        }

    }

}
