/* 
 * Amber API Server
 *
 * Boon Logic Amber API Server
 *
 * OpenAPI spec version: 1.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BoonAmber.Api;
using BoonAmber.Model;
using BoonAmber.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BoonAmber.Test
{
    /// <summary>
    ///  Class for testing StreamingEndpointUsageInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class StreamingEndpointUsageInfoTests
    {
        // TODO uncomment below to declare an instance variable for StreamingEndpointUsageInfo
        //private StreamingEndpointUsageInfo instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of StreamingEndpointUsageInfo
            //instance = new StreamingEndpointUsageInfo();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of StreamingEndpointUsageInfo
        /// </summary>
        [Test]
        public void StreamingEndpointUsageInfoInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" StreamingEndpointUsageInfo
            //Assert.IsInstanceOfType<StreamingEndpointUsageInfo> (instance, "variable 'instance' is a StreamingEndpointUsageInfo");
        }


        /// <summary>
        /// Test the property 'CallsTotal'
        /// </summary>
        [Test]
        public void CallsTotalTest()
        {
            // TODO unit test for the property 'CallsTotal'
        }
        /// <summary>
        /// Test the property 'CallsThisPeriod'
        /// </summary>
        [Test]
        public void CallsThisPeriodTest()
        {
            // TODO unit test for the property 'CallsThisPeriod'
        }
        /// <summary>
        /// Test the property 'SamplesTotal'
        /// </summary>
        [Test]
        public void SamplesTotalTest()
        {
            // TODO unit test for the property 'SamplesTotal'
        }
        /// <summary>
        /// Test the property 'SamplesThisPeriod'
        /// </summary>
        [Test]
        public void SamplesThisPeriodTest()
        {
            // TODO unit test for the property 'SamplesThisPeriod'
        }
        /// <summary>
        /// Test the property 'LastCalled'
        /// </summary>
        [Test]
        public void LastCalledTest()
        {
            // TODO unit test for the property 'LastCalled'
        }

    }

}
