/* 
 * Amber API Server
 *
 * Boon Logic Amber API Server
 *
 * OpenAPI spec version: 1.0.3
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 */

using NUnit.Framework;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using BoonAmber.Api;
using BoonAmber.Model;
using BoonAmber.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace BoonAmber.Test
{
    /// <summary>
    ///  Class for testing Version
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by Swagger Codegen.
    /// Please update the test case below to test the model.
    /// </remarks>
    [TestFixture]
    public class VersionTests
    {
        // TODO uncomment below to declare an instance variable for Version
        //private Version instance;

        /// <summary>
        /// Setup before each test
        /// </summary>
        [SetUp]
        public void Init()
        {
            // TODO uncomment below to create an instance of Version
            //instance = new Version();
        }

        /// <summary>
        /// Clean up after each test
        /// </summary>
        [TearDown]
        public void Cleanup()
        {

        }

        /// <summary>
        /// Test an instance of Version
        /// </summary>
        [Test]
        public void VersionInstanceTest()
        {
            // TODO uncomment below to test "IsInstanceOfType" Version
            //Assert.IsInstanceOfType<Version> (instance, "variable 'instance' is a Version");
        }


        /// <summary>
        /// Test the property 'Release'
        /// </summary>
        [Test]
        public void ReleaseTest()
        {
            // TODO unit test for the property 'Release'
        }
        /// <summary>
        /// Test the property 'ApiVersion'
        /// </summary>
        [Test]
        public void ApiVersionTest()
        {
            // TODO unit test for the property 'ApiVersion'
        }
        /// <summary>
        /// Test the property 'Builder'
        /// </summary>
        [Test]
        public void BuilderTest()
        {
            // TODO unit test for the property 'Builder'
        }
        /// <summary>
        /// Test the property 'ExpertApi'
        /// </summary>
        [Test]
        public void ExpertApiTest()
        {
            // TODO unit test for the property 'ExpertApi'
        }
        /// <summary>
        /// Test the property 'ExpertCommon'
        /// </summary>
        [Test]
        public void ExpertCommonTest()
        {
            // TODO unit test for the property 'ExpertCommon'
        }
        /// <summary>
        /// Test the property 'NanoSecure'
        /// </summary>
        [Test]
        public void NanoSecureTest()
        {
            // TODO unit test for the property 'NanoSecure'
        }
        /// <summary>
        /// Test the property 'SwaggerUi'
        /// </summary>
        [Test]
        public void SwaggerUiTest()
        {
            // TODO unit test for the property 'SwaggerUi'
        }

    }

}
